import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  items: [],
};

export const todoSlice = createSlice({
  name: 'todos',
  initialState,
  reducers: {
    // Redux Toolkit utilizes the 'Immer' library internally.
    // This allows us to write "mutating" logic in reducers (like state.items.push)
    // while actually returning a brand new immutable state object under the hood.
    addTodo: (state, action) => {
      state.items.push({
        id: crypto.randomUUID(), // Using the native crypto API to generate a unique ID
        text: action.payload,    // action.payload carries the user's input string
        completed: false,
      });
    },
    
    deleteTodo: (state, action) => {
      // Reassigning state.items using filter acts as an Immutable update.
      // action.payload is the ID of the todo to remove.
      state.items = state.items.filter(todo => todo.id !== action.payload);
    },
    
    toggleStatus: (state, action) => {
      // We look up the specific item by ID.
      const todo = state.items.find(todo => todo.id === action.payload);
      if (todo) {
        // Thanks to Immer, we can directly toggle the property without spreading object copies!
        todo.completed = !todo.completed;
      }
    },
    
    editTodo: (state, action) => {
      // Destructure expected values from payload object
      const { id, newText } = action.payload;
      const todo = state.items.find(todo => todo.id === id);
      if (todo) {
        todo.text = newText;
      }
    }
  },
});

// Export the action creators generated by createSlice
export const { addTodo, deleteTodo, toggleStatus, editTodo } = todoSlice.actions;

// Export the reducer directly for the store configuration
export default todoSlice.reducer;
